// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blog161.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20190808211917_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blog161.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Alimentação"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Tecnologia"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Lifestyle"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Jogos"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Espeorte"
                        });
                });

            modelBuilder.Entity("Blog161.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor");

                    b.Property<DateTime>("Data");

                    b.Property<string>("Descricao");

                    b.Property<int>("MensagemId");

                    b.Property<string>("Titulo");

                    b.HasKey("Id");

                    b.HasIndex("MensagemId");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("Blog161.Models.Mensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaId");

                    b.Property<DateTime>("Data");

                    b.Property<string>("Descricao");

                    b.Property<string>("Titulo");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Mensagem");
                });

            modelBuilder.Entity("Blog161.Models.Comentario", b =>
                {
                    b.HasOne("Blog161.Models.Mensagem", "Mensagem")
                        .WithMany("Comentarios")
                        .HasForeignKey("MensagemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Blog161.Models.Mensagem", b =>
                {
                    b.HasOne("Blog161.Models.Categoria", "Categoria")
                        .WithMany("Mensagens")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
